name: mamba_{{cookiecutter.__project_slug}}
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python={{cookiecutter.python_ver}}
  - pip
  - poetry
  - poetry-plugin-export
  - make
  - git >=2.30.0
  - yq
  - cmake
  - c-compiler
  - cxx-compiler
  - llvmdev
  - llvmlite
  - numba
{%- if cookiecutter.r_ver != "none" %}
  - r-base={{cookiecutter.r_ver}}
  - r-renv
  - r-irkernel
  - r-testthat
  - r-styler
  - r-lintr
  - r-devtools
  - r-pkgdown
  - r-roxygen2
  - r-rmarkdown
  - r-knitr
  - r-biocmanager
  - bioconductor-biocversion
{%- endif %}
