name: mamba_{{cookiecutter.__project_slug}}
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python={{cookiecutter.python_ver}}
  - poetry
  - make
  - git
  - yq
{%- if cookiecutter.r_ver != "none" %}
  - r-base={{cookiecutter.r_ver}}
  - cmake
  - pkg-config
  - libxml2
  - libcurl
  - openssl
  - zeromq
  - libuv
  - glpk
  - pandoc
  - libgit2
  - glib
  - harfbuzz
  - fribidi
  - freetype
  - libpng
  - libjpeg-turbo
{%- endif %}
