[tool.poetry]
name = "{{ cookiecutter.__project_slug }}"
version = "0.0.1"
description = "{{ cookiecutter.description }}"
authors = ["{{ cookiecutter.author_name }} <{{ cookiecutter.email }}>"]
readme = "README.md"
{%- if cookiecutter.create_package == "false" %}
package-mode = false
{%- endif %}

[tool.poetry.dependencies]
python = ">={{ cookiecutter.python_ver }},<4.0"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
target-version = "{{ cookiecutter.__pyver }}"

[tool.ruff.lint]
select = ["E", "F", "I"]
fixable = ["ALL"]

[tool.ruff.lint.isort]
known-first-party = ["{{ cookiecutter.__project_slug }}"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.pytest.ini_options]
addopts = ["--doctest-modules", "-v", "--durations=10"]
testpaths = [
    "tests",
    "{{cookiecutter.__project_slug}}_tools",
{%- if cookiecutter.create_package == "true" %}
    "src",
{%- endif %}
]
norecursedirs = [".ipynb_checkpoints", "docs", "renv", ".venv", ".git", ".github"]
