version: "3"
services:
  jupyterlab:
    build:
      context: .
    user: root
    ports:
      - "8888:8888"
    volumes:
      - "./codes:/home/jovyan/codes"
      - "./utils:/home/jovyan/utils"
      - "./data:/home/jovyan/data"
      - "./outputs:/home/jovyan/outputs"
    environment:
      NB_UID: YOUR_ID
      GRANT_SUDO: "yes"
    command: start.sh jupyter lab --NotebookApp.password='sha256:a2a45f7ca6fb:c7309099cdc02959058e34589c664559364a21da58b07f263eedd16b84629a99'
