name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Conda env
        uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('**/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Setup Mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          use-mamba: true
          pkgs-dirs: ~/conda_pkgs_dir
          channels: conda-forge,nodefaults
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --with dev --no-interaction --no-root

      - name: Run pre-commit hooks
        run: poetry run pre-commit run --all-files

      - name: Run Tests (Pytest)
        shell: bash -el {0}
        run: make test
